### ISSUE TITLE
Error when using unindexed tables

### ISSUE THREAD

**Issue by elihugarret** [hishamhm/tabular#1]
Hi Hisham! was trying this cool lib and found this error:

```lua
tabular{{a=1, b=2}, {b=5, c=3, d=4}, {34}}
```

`/usr/local/share/lua/5.3/tabular.lua:26: attempt to index a number value (local 's')
stack traceback:
	/usr/local/share/lua/5.3/tabular.lua:26: in upvalue 'strlen'
	/usr/local/share/lua/5.3/tabular.lua:169: in function </usr/local/share/lua/5.3/tabular.lua:148>
	(...tail calls...)
	/usr/local/share/lua/5.3/tabular.lua:279: in function 'tabular.show'
	(...tail calls...)
	[C]: in ?`

**Comment by hishamhm** [comment]
Fixed by commit 2e115761326eb6009ad80c571442db83c80dbea2 — thank you for the report!

By the way, I also made some tweaks in the tl repo and expanded the README, it should be easier to run now! Give it a try! :)
